{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.0.jar",
          "url": "customtransformplugin-1.0.0.jar",
          "size": 4884,
          "sha512": "e80601320c3f8278cfa6cfafe8d1e3c7c566982bcf07fde927e529f61d95b5680c74f5f35e499d4e03b1a45a5de0514650af47762a5ab4302abb6f7237db046c",
          "sha256": "1c59f655cc5e60b8f72f29b7d22d853ceb731e5bed88e758f6b1b74afc1c762c",
          "sha1": "215a6b0d75f663dc7341a8db79c2aba516fb5a11",
          "md5": "9903a76d691d992e1a09a2b98d3b7c5e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.0.jar",
          "url": "customtransformplugin-1.0.0.jar",
          "size": 4884,
          "sha512": "e80601320c3f8278cfa6cfafe8d1e3c7c566982bcf07fde927e529f61d95b5680c74f5f35e499d4e03b1a45a5de0514650af47762a5ab4302abb6f7237db046c",
          "sha256": "1c59f655cc5e60b8f72f29b7d22d853ceb731e5bed88e758f6b1b74afc1c762c",
          "sha1": "215a6b0d75f663dc7341a8db79c2aba516fb5a11",
          "md5": "9903a76d691d992e1a09a2b98d3b7c5e"
        }
      ]
    }
  ]
}
