{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-unspecified.jar",
          "url": "customtransformplugin-unspecified.jar",
          "size": 28976,
          "sha512": "36b19244d42c5ed40b114811e15c08c287eb77ae9b38aab3108858fc842671d55a76480b3751af559a7b1ef8bcd7edce0e8eb1be993bd991e62f7f6987f7c8a5",
          "sha256": "569e994d5ae92816287e4e2e63445f01f2574dbf25fa2be56de2ca741d3bfe79",
          "sha1": "31dee50b53782285416b246e2395cfbe1158eda0",
          "md5": "56bc240abc13ef4b2590d6cc55ce8d8a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.29.2-GA"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-unspecified.jar",
          "url": "customtransformplugin-unspecified.jar",
          "size": 28976,
          "sha512": "36b19244d42c5ed40b114811e15c08c287eb77ae9b38aab3108858fc842671d55a76480b3751af559a7b1ef8bcd7edce0e8eb1be993bd991e62f7f6987f7c8a5",
          "sha256": "569e994d5ae92816287e4e2e63445f01f2574dbf25fa2be56de2ca741d3bfe79",
          "sha1": "31dee50b53782285416b246e2395cfbe1158eda0",
          "md5": "56bc240abc13ef4b2590d6cc55ce8d8a"
        }
      ]
    }
  ]
}
