{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.4.jar",
          "url": "customtransformplugin-1.0.4.jar",
          "size": 14645,
          "sha512": "3dbae12b9f07bc1cef7b4f113b84c093dc2dc8076f90e2e8e83de793fc5f880cfa7cacf4eda74364d3b8cf28d40ced35551ae675ab1c47b2e1d51282772dee13",
          "sha256": "b7cc8d5262678b45ba97da15c2b421ae8122d37ecd325d0f0ea501170f212011",
          "sha1": "24fbf2bddad86ff0af7bb014abbee8cb3f322625",
          "md5": "dcd10be145765558c1e4bce9419484ca"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.4.jar",
          "url": "customtransformplugin-1.0.4.jar",
          "size": 14645,
          "sha512": "3dbae12b9f07bc1cef7b4f113b84c093dc2dc8076f90e2e8e83de793fc5f880cfa7cacf4eda74364d3b8cf28d40ced35551ae675ab1c47b2e1d51282772dee13",
          "sha256": "b7cc8d5262678b45ba97da15c2b421ae8122d37ecd325d0f0ea501170f212011",
          "sha1": "24fbf2bddad86ff0af7bb014abbee8cb3f322625",
          "md5": "dcd10be145765558c1e4bce9419484ca"
        }
      ]
    }
  ]
}
