{
  "formatVersion": "1.1",
  "component": {
    "group": "GradleTransformDemo",
    "module": "customtransformplugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "customtransformplugin-1.0.6.jar",
          "url": "customtransformplugin-1.0.6.jar",
          "size": 14606,
          "sha512": "9701d0c0828f7827efb8882ff267c92a625a15d0299e8d25168bddeaf2bddaa92659e1866cbd69179ef6fc5ef2e1e3820f05a0437b66518eaebb165491abb820",
          "sha256": "067469b2828efae2bd41401de59ce337a2a836f18caa3711bba076f854f609e7",
          "sha1": "df3c37271a4b86157a4c75e5b91d34601511c863",
          "md5": "abdc0a855fc7f2c11e096c35043554fc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "com.android.tools",
          "module": "common",
          "version": {
            "requires": "30.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "customtransformplugin-1.0.6.jar",
          "url": "customtransformplugin-1.0.6.jar",
          "size": 14606,
          "sha512": "9701d0c0828f7827efb8882ff267c92a625a15d0299e8d25168bddeaf2bddaa92659e1866cbd69179ef6fc5ef2e1e3820f05a0437b66518eaebb165491abb820",
          "sha256": "067469b2828efae2bd41401de59ce337a2a836f18caa3711bba076f854f609e7",
          "sha1": "df3c37271a4b86157a4c75e5b91d34601511c863",
          "md5": "abdc0a855fc7f2c11e096c35043554fc"
        }
      ]
    }
  ]
}
